version: "3"

services:

  server:

    build: server/

    command: python3 ./final_project.py

    ports:
      - 8080:8080

  client:

    build: client/

    command: sh -c "pytest -v -s test_all.py --disable-warnings; tail -f tail.txt"

    network_mode: host
 
    depends_on:
      - server