version: "3"

services:

  server:

    build: server/

    command: python3 ./final_project.py

    ports:
      - 1234:1234

  client:

    build: client/

    command: pytest -v -s test_all.py --disable-warnings

    network_mode: host
 
    depends_on:
      - server